language: python
python: 3.6

install: "pip3 install flake8 mypy"
script:
  - flake8 src/ || travis_terminate 1
  - ./.travis/check_init_py.sh src/ || travis_terminate 1
  - MYPYPATH=$(pwd)/src mypy -p ja --no-strict-optional --strict
